name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Docker Image Build for AMD64
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
      uses: docker/build-push-action@v1.1.1
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        # Docker repository to tag the image with
        repository: skynet
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest
        # Path to the build context
        path: docker
        # Platforms
        platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
        # Adds labels with git repository information to the built image
        add_git_labels: true
        # Whether to push the image
        push: true
